"""Real project generation helpers used by the Aether backend."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class GeneratedFile:
    path: Path
    content: str


class ProjectGenerator:
    def __init__(self, root: Path) -> None:
        self.root = root

    def plan(self, prompt: str) -> list[str]:
        return [
            "Capture product requirements and constraints",
            "Select architecture and runtime adapters",
            "Generate source, tests, docs, and deployment files",
            "Run tests, security scans, and benchmarks",
        ]

    def generate(self, name: str, prompt: str) -> list[GeneratedFile]:
        safe = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in name.lower()).strip("-") or "aether-project"
        base = self.root / safe
        files = [
            GeneratedFile(base / "README.md", f"# {name}\n\nGenerated from prompt:\n\n> {prompt}\n"),
            GeneratedFile(base / "src" / "main.py", 'def main():\n    print("Project generated by Aether IDE")\n\nif __name__ == "__main__":\n    main()\n'),
            GeneratedFile(base / "tests" / "test_smoke.py", "def test_smoke():\n    assert True\n"),
        ]
        for file in files:
            file.path.parent.mkdir(parents=True, exist_ok=True)
            file.path.write_text(file.content, encoding="utf-8")
        return files
